version: '3.9'

services:
  goods_service:
    build:
      context: ./goods_service
      dockerfile: Dockerfile
    container_name: goods_service
    env_file:
      - ./goods_service/.env
    ports:
      - "8001:8000"
    depends_on:
      - goods_db
    networks:
      - app_network

  orders_service:
    build:
      context: ./orders_service
      dockerfile: Dockerfile
    container_name: orders_service
    env_file:
      - ./orders_service/.env
    ports:
      - "8002:8000"
    depends_on:
      - orders_db
    networks:
      - app_network

  goods_db:
    image: postgres
    container_name: goods_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goods_db
    ports:
      - "5344:5432"
    volumes:
      - goods_db_data:/var/lib/postgresql/data
    networks:
      - app_network

  orders_db:
    image: postgres
    container_name: orders_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5345:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  goods_db_data:
  orders_db_data:

